version: '3.9'

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=2nd_project
      - MARIADB_USER=beyond
      - MARIADB_PASSWORD=beyond
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DEV_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/2nd_project
      - DEV_DB_USERNAME=beyond
      - DEV_DB_PASSWORD=beyond
      - DEV_REDIS_PASSWORD=
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - JWT_SECRET=fowijpf2oi3j23wieofjwoeiekwfjowjfoiejfowjfiwjfj==

      # Gmail SMTP 설정
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=kimeodml0546@gmail.com
      - SPRING_MAIL_PASSWORD=phmyxagruspinbuh  # 공백 없는 App Password
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure

  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mariadb_data:
  redis_data:
