version: "3.9"

networks:
  backend:
    driver: bridge

services:
  lumi:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPOSITORY}
    container_name: lumi
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JWT_SECRET: ${JWT_SECRET}
      TZ:  Asia/Seoul
    volumes:
      - ${DEV_UPLOAD_DIR}:/spring-boot/uploads
    depends_on:
      - mariadb
      - redis
    networks:
      - backend

  mariadb:
    image: mariadb:11.8.2
    container_name: mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      TZ: Asia/Seoul
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend

  redis:
    image: redis:8.2.1
    container_name: redis
    restart: always
    volumes:
      - ./redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend

volumes:
  db_data:
