apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins-fiveguys
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - name: web
      port: 8080
      targetPort: 8080
      nodePort: 30030
    - name: agent
      port: 50000
      targetPort: 50000
